{{- if .Values.webhook.enabled }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "misp-operator.fullname" . }}-validating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ include "misp-operator.fullname" . }}-webhook-service
        namespace: {{ include "misp-operator.namespace" . }}
        path: /validate-misp-k8s-pascaliske-dev-v1alpha1-mispinstance
    failurePolicy: Fail
    name: vmispinstance-v1alpha1.kb.io
    rules:
      - apiGroups:
          - misp.k8s.pascaliske.dev
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - mispinstances
    sideEffects: None
{{- end }}
