{{- if .Values.webhook.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "misp-operator.fullname" . }}-webhook-service
  namespace: {{ include "misp-operator.namespace" . }}
  labels:
    {{- include "misp-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: webhook
      port: 443
      targetPort: webhook
      protocol: TCP
  selector:
    {{- include "misp-operator.selectorLabels" . | nindent 4 }}
{{- end }}
