---
apiVersion: misp.k8s.pascaliske.dev/v1alpha1
kind: MispSyncConfig
metadata:
  name: mispsyncconfig-sample
  labels:
    app.kubernetes.io/name: misp-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  organisation:
    name: DemoOrg
  user:
    credentialsSecretRef:
      name: misp-sync-user
  instanceRef:
    name: misp-sample
    namespace: misp-instance-a
  remoteInstanceRef:
    name: misp-sample
    namespace: misp-instance-b
