---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Release Please

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        id: release
        with:
          config-file: .github/release-please-config.json
          manifest-file: .release-please-manifest.json
          token: '${{ secrets.RELEASE_PLEASE_TOKEN }}'

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        if: ${{ steps.release.outputs.release_created }}
        with:
          persist-credentials: false

      - name: Publish installer manifest
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          make build-installer IMG=ghcr.io/pascaliske/misp-operator:${{ steps.release.outputs.tag_name }}
          gh release upload ${{ steps.release.outputs.tag_name }} ./dist/install.yaml
